# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRI-Phantom.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 480)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.text_2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.text_2.setFont(font)
        self.text_2.setObjectName("text_2")
        self.verticalLayout_5.addWidget(self.text_2)
        self.l1 = QtWidgets.QLabel(Dialog)
        self.l1.setMinimumSize(QtCore.QSize(0, 0))
        self.l1.setMaximumSize(QtCore.QSize(512, 512))
        self.l1.setFrameShape(QtWidgets.QFrame.Box)
        self.l1.setText("")
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.verticalLayout_5.addWidget(self.l1)
        self.text_5 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.text_5.setFont(font)
        self.text_5.setObjectName("text_5")
        self.verticalLayout_5.addWidget(self.text_5)
        self.l2 = QtWidgets.QLabel(Dialog)
        self.l2.setMinimumSize(QtCore.QSize(0, 0))
        self.l2.setMaximumSize(QtCore.QSize(512, 512))
        self.l2.setStyleSheet("border-color: rgb(204, 0, 0);")
        self.l2.setFrameShape(QtWidgets.QFrame.Box)
        self.l2.setText("")
        self.l2.setScaledContents(True)
        self.l2.setObjectName("l2")
        self.verticalLayout_5.addWidget(self.l2)
        self.text_6 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.text_6.setFont(font)
        self.text_6.setObjectName("text_6")
        self.verticalLayout_5.addWidget(self.text_6)
        self.l3 = QtWidgets.QLabel(Dialog)
        self.l3.setMaximumSize(QtCore.QSize(512, 512))
        self.l3.setFrameShape(QtWidgets.QFrame.Box)
        self.l3.setText("")
        self.l3.setScaledContents(True)
        self.l3.setObjectName("l3")
        self.verticalLayout_5.addWidget(self.l3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 8, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.cb = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb.sizePolicy().hasHeightForWidth())
        self.cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("NanumBarunGothic")
        self.cb.setFont(font)
        self.cb.setEditable(False)
        self.cb.setObjectName("cb")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.setItemText(9, "")
        self.gridLayout.addWidget(self.cb, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 0, 1, 1)
        self.cb2 = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb2.sizePolicy().hasHeightForWidth())
        self.cb2.setSizePolicy(sizePolicy)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.gridLayout.addWidget(self.cb2, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 5, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 0, 1, 1)
        self.graphicsView = PlotWidget(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 7, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.cb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.text_2.setText(_translate("Dialog", "                Phantom"))
        self.text_5.setText(_translate("Dialog", "                  T1 Image"))
        self.text_6.setText(_translate("Dialog", "              T2 Image"))
        self.cb.setCurrentText(_translate("Dialog", "Select Phantom"))
        self.cb.setItemText(0, _translate("Dialog", "Select Phantom"))
        self.cb.setItemText(1, _translate("Dialog", "Shepp-Logan phantom"))
        self.cb.setItemText(2, _translate("Dialog", "Piecewise-Smooth Shepp-Logan phantom"))
        self.cb.setItemText(3, _translate("Dialog", "Defrise phantom with vertical ellipses"))
        self.cb.setItemText(4, _translate("Dialog", "\'QRM\' phantom (ellipses)"))
        self.cb.setItemText(5, _translate("Dialog", "1 cone"))
        self.cb.setItemText(6, _translate("Dialog", "1 rectangular"))
        self.cb.setItemText(7, _translate("Dialog", "composite"))
        self.cb.setItemText(8, _translate("Dialog", "composite of 6 gaussians + 1 parabola"))
        self.lineEdit_4.setText(_translate("Dialog", "TR"))
        self.cb2.setItemText(0, _translate("Dialog", "Time Selection"))
        self.lineEdit_5.setText(_translate("Dialog", "TE"))
        self.lineEdit_7.setText(_translate("Dialog", "Theta"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
